# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "998dba39416cecb39d8c38b2e839c103"
name = "shop-app"
application_url = "https://drew-student-ourselves-wrestling.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "bonobo-hab.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://drew-student-ourselves-wrestling.trycloudflare.com/auth/callback",
  "https://drew-student-ourselves-wrestling.trycloudflare.com/auth/shopify/callback",
  "https://drew-student-ourselves-wrestling.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
